config/routes.rb
Rails.application.routes.draw do

  get 'admin_user/index'
  get 'admin_user/new'
  get 'admin_user/create'
  get 'admin_user/edit'
  get 'admin_user/update'
  get 'admin_user/destroy'
  root 'demo#index'
  get 'admin', :to => 'access#menu'
  get 'access/menu'
  get 'access/login'
  post 'access/attempt_login'
  get 'access/logout'

  resources :section_edits
  resources :sections
  resources :pages
  resources :subjects
  resources :users


end

app/views/pages/_form.html.erb
<%= form_with(model: page, local: true) do |form| %>
  <% if page.errors.any? %>
    <div id="error-explanation">
      <h2><%= pluralize(page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :subject_id %>
    <%= form.select(:subject_id, @subjects.map {|s| [s.name, s.id]})%>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :permalink %>
    <%= form.text_field :permalink %>
  </div>

  <div class="field">
    <%= form.label :position %>
    <%= form.select(:position, 1..@page_count) %>
  </div>

  <div class="field">
    <%= form.label :visible %>
    <%= form.check_box :visible %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<% @page_title = "Edit Page" %>
<h2>Editing Page</h2>
<!--@page is being passed from the controller-->
<%= render 'form', page: @page %>

<%= link_to 'Show', @page %>
<%= link_to 'Back', pages_path %>

app/views/pages/index.html.erb
<% @page_title = " All Pages" %>
<%= link_to("<< Back to Menu", admin_path, :class => 'back-link') %>
<div class="pages index">

<h2>Pages</h2>

  <%= image_tag('plus_sign.png', :size=>'11x11', :alt => '+') %>
  <%= link_to 'New Page', new_page_path %>

  <table class="listing">
    <thead>
      <tr class="header">
        <th>Subject</th>
        <th>Name</th>
        <th>Permalink</th>
        <th>Position</th>
        <th>Visible</th>
        <th>Sections</th>
        <th colspan="3">Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @pages.each do |page| %>
        <tr>
          <td><%= page.subject.name %></td>
          <td><%= page.name %></td>
          <td><%= page.permalink %></td>
          <td><%= page.position %></td>
          <td><%= status_tag(page.visible) %></td>
          <td><%= page.sections.size %></td>
          <td><%= link_to 'Show', page %></td>
          <td><%= link_to 'Edit', edit_page_path(page) %></td>
          <td><%= link_to 'Destroy', page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

</div>

app/views/pages/new.html.erb
<% @page_title = "New Page" %>

<h2>New Page</h2>
<%= link_to '<< Back to list', pages_path %>
<%= render 'form', page: @page %>

app/views/pages/show.html.erb
<% @page_title = "Show Page" %>

<p>
  <strong>Subject:</strong>
  <%= @page.subject.name %>
</p>

<p>
  <strong>Name:</strong>
  <%= @page.name %>
</p>

<p>
  <strong>Permalink:</strong>
  <%= @page.permalink %>
</p>

<p>
  <strong>Position:</strong>
  <%= @page.position %>
</p>

<p>
  <strong>Visible:</strong>
  <%= @page.visible ? 'Yes' : 'No' %>
</p>


<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'Back', pages_path %>