config/routes.rb
Rails.application.routes.draw do

  get 'admin_user/index'
  get 'admin_user/new'
  get 'admin_user/create'
  get 'admin_user/edit'
  get 'admin_user/update'
  get 'admin_user/destroy'
  root 'demo#index'
  get 'admin', :to => 'access#menu'
  get 'access/menu'
  get 'access/login'
  post 'access/attempt_login'
  get 'access/logout'

  resources :section_edits
  resources :sections
  resources :pages
  resources :subjects
  resources :users


end

app/models/subject.rb
class Subject < ApplicationRecord

  has_many :pages

  scope :visible, lambda{ where(:visible => true) }
  scope :invisible, lambda{ where(:visible => false ) }
  scope :sorted, lambda{order("position ASC")}
  scope :newest_first, lambda{order(:created_at => desc)}
  scope :search, lambda{|query| where(["name LIKE ?", "%#{query}%" ])}


  validates_presence_of :name
  validates_length_of :name, :maximum => 255

end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: [:show, :edit, :update, :destroy]

  layout 'admin'
  # GET /subjects
  # GET /subjects.json
  def index
    @subjects = Subject.sorted
  end

  # GET /subjects/1
  # GET /subjects/1.json
  def show
    #we don't need this as there is before_action above :set_subject which is defined later as Subject.find(params[:id])
    #@subject = Subject.find(params[:id])
  end

  # GET /subjects/new
  def new
    @subject = Subject.new(:name =>"Default")
    @subject_count = Subject.count + 1
  end

  # GET /subjects/1/edit
  def edit
    @subject_count = Subject.count
  end

  # POST /subjects
  # POST /subjects.json
  def create

    # Instantiate a new object using form parameters
    @subject = Subject.new(subject_params)

    respond_to do |format|
      # Save the object
      # If save succeeds, redirect to the index action
      if @subject.save
        format.html { redirect_to subjects_path, notice: "Subject '#{@subject.name}' was successfully created." }
        format.json { render :show, status: :created, location: @subject }
      # If save fails, redisplay the form so the user can fix the problem
      else
        #render('new')
        @subject_count = Subject.count + 1
        format.html { render :new }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subjects/1
  # PATCH/PUT /subjects/1.json
  def update
    #we don't need this as there is before_action above :set_subject which is defined later as Subject.find(params[:id])
    #@subject = Subject.find(params[:id])
    respond_to do |format|
      if @subject.update(subject_params) # we use the whitelisted value
        format.html { redirect_to subjects_path, notice: "Subject '#{@subject.name}' was successfully updated." }
        format.json { render :show, status: :ok, location: @subject }
      else
        @subject_count = Subject.count
        format.html { render :edit }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1
  # DELETE /subjects/1.json
  def destroy
    @subject.destroy
    respond_to do |format|
      format.html { redirect_to subjects_path, notice: "Subject '#{@subject.name}' was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subject
      @subject = Subject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subject_params
      params.require(:subject).permit(:name, :position, :visible)
    end
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/_form.html.erb
<%= form_with(model: subject, local: true) do |form| %>
  <% if subject.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(subject.errors.count, "error") %> prohibited this subject from being saved:</h2>

      <ul>
      <% subject.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :position %>
    <%= form.select(:position, 1..@subject_count) %>
  </div>

  <div class="field">
    <%= form.label :visible %>
    <%= form.check_box :visible %>
  </div>

<!--  <div class="field">-->
    <%#= form.label :Created %>
    <%#= form.datetime_select(:created_at, :order=> [:month, :day, :year] ) %>
<!--  </div>-->

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/subjects/edit.html.erb
<% @page_title = "Edit subject" %>

<h2>Update Subject</h2>
<%= link_to '<< Back to list', subjects_path %>
<%= render 'form', subject: @subject %>

<%= link_to 'Show', @subject %>

app/views/subjects/index.html.erb
<% @page_title = " All Subjects" %>
<%= link_to("<< Back to Menu", admin_path, :class => 'back-link') %>
<div class="subjects index">
  <h2>Subjects</h2>
  <%= image_tag('plus_sign.png', :size=>'11x11', :alt => '+') %>
  <%= link_to 'New Subject', new_subject_path %>
  <table class="listing" summary="Subject list">
    <thead>
      <tr class="header">
        <th>Name</th>
        <th>Position</th>
        <th>Visible</th>
        <th>Pages</th>
        <th colspan="3">Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @subjects.each do |subject| %>
        <tr>
          <td><%= subject.name %></td>
          <td><%= subject.position %></td>
          <td><%= status_tag(subject.visible) %></td>
          <td><%= subject.pages.size %></td>
          <td><%= link_to 'Show', subject_path(subject) %></td>
          <td><%= link_to 'Edit', edit_subject_path(subject) %></td>
          <td><%= link_to 'Destroy', subject, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>
</div>
<%#= link_to('Roar', '#', :onclick => "jsRoar('JavaScript'); return true;") %>

app/views/subjects/new.html.erb
<% @page_title = "New Subject" %>

<h2>New Subject</h2>
<%= link_to '<< Back to list', subjects_path %>

<%= render 'form', subject: @subject %>

app/views/subjects/show.html.erb
<% @page_title = "Show Subject" %>

<h2>Show Subject</h2>
<div class ="subjects show">
  <%= link_to '<< Back to list', subjects_path %>
  <p>
    <strong>Name:</strong>
    <%= @subject.name %>
  </p>

  <p>
    <strong>Position:</strong>
    <%= @subject.position %>
  </p>

  <p>
    <strong>Visible:</strong>
    <%= @subject.visible ? 'Yes': 'No' %>
  </p>
  <p>
    <strong>Created: </strong>
    <%=@subject.created_at %>
  </p>
  <p>
    <strong>Updated: </strong>
    <%=@subject.updated_at %>
  </p>

  <%= link_to 'Edit', edit_subject_path(@subject) %>

</div>