config/routes.rb
Rails.application.routes.draw do

  get 'admin_user/index'
  get 'admin_user/new'
  get 'admin_user/create'
  get 'admin_user/edit'
  get 'admin_user/update'
  get 'admin_user/destroy'
  root 'demo#index'
  get 'admin', :to => 'access#menu'
  get 'access/menu'
  get 'access/login'
  post 'access/attempt_login'
  get 'access/logout'

  resources :section_edits
  resources :sections
  resources :pages
  resources :subjects
  resources :users


end

app/models/section_edit.rb
class SectionEdit < ApplicationRecord

  belongs_to :user
  belongs_to :section

end

app/controllers/section_edits_controller.rb
class SectionEditsController < ApplicationController
  before_action :set_section_edit, only: [:show, :edit, :update, :destroy]

  layout 'admin'

  # GET /section_edits
  # GET /section_edits.json
  def index
    @section_edits = SectionEdit.all
  end

  # GET /section_edits/1
  # GET /section_edits/1.json
  def show
  end

  # GET /section_edits/new
  def new
    @section_edit = SectionEdit.new
  end

  # GET /section_edits/1/edit
  def edit
  end

  # POST /section_edits
  # POST /section_edits.json
  def create
    @section_edit = SectionEdit.new(section_edit_params)

    respond_to do |format|
      if @section_edit.save
        format.html { redirect_to @section_edit, notice: 'Section edit was successfully created.' }
        format.json { render :show, status: :created, location: @section_edit }
      else
        format.html { render :new }
        format.json { render json: @section_edit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /section_edits/1
  # PATCH/PUT /section_edits/1.json
  def update
    respond_to do |format|
      if @section_edit.update(section_edit_params)
        format.html { redirect_to @section_edit, notice: 'Section edit was successfully updated.' }
        format.json { render :show, status: :ok, location: @section_edit }
      else
        format.html { render :edit }
        format.json { render json: @section_edit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /section_edits/1
  # DELETE /section_edits/1.json
  def destroy
    @section_edit.destroy
    respond_to do |format|
      format.html { redirect_to section_edits_url, notice: 'Section edit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_section_edit
      @section_edit = SectionEdit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def section_edit_params
      params.require(:section_edit).permit(:user_id, :section_id, :summary)
    end
end

app/helpers/section_edits_helper.rb
module SectionEditsHelper
end

app/views/section_edits/_form.html.erb
<%= form_for(@section_edit, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @section_edit.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@section_edit.errors.count, "error") %> prohibited this section_edit from being saved:</h4>

      <ul>
      <% @section_edit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :user_id, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :user_id, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :section_id, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :section_id, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :summary, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :summary, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/section_edits/edit.html.erb
<div class="page-header">
  <%= link_to section_edits_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @section_edit, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing section_edit</h1>
</div>

<%= render 'form' %>

app/views/section_edits/index.html.erb
<div class="page-header">
  <%= link_to new_section_edit_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Section edit
  <% end %>
  <h1>Listing section_edits</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>User</th>
            <th>Section</th>
            <th>Summary</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @section_edits) do |section_edit| %>
            <td><%= section_edit.user_id %></td>
            <td><%= section_edit.section_id %></td>
            <td><%= section_edit.summary %></td>
            <td><%= link_to 'Show', section_edit %></td>
        <td><%= link_to 'Edit', edit_section_edit_path(section_edit) %></td>
        <td><%= link_to 'Destroy', section_edit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/section_edits/new.html.erb
<div class="page-header">
  <%= link_to section_edits_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New section_edit</h1>
</div>

<%= render 'form' %>

app/views/section_edits/show.html.erb
<div class="page-header">
  <%= link_to section_edits_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_section_edit_path(@section_edit), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show section_edit</h1>
</div>

<dl class="dl-horizontal">
  <dt>User:</dt>
  <dd><%= @section_edit.user_id %></dd>

  <dt>Section:</dt>
  <dd><%= @section_edit.section_id %></dd>

  <dt>Summary:</dt>
  <dd><%= @section_edit.summary %></dd>

</dl>